### ISSUE TITLE
[UI] Chart Improvement

### ISSUE THREAD

**Issue by cobo2bofb** [pampeanodev/btcretirementcalc#11]
[Improvement] [UI]

Adding the inflation growth to the Chart is a must. The idea is to be able to visually compare inflation vs Bitcoin Growth, along with USD/Savings growth.

Users should be able to allow or disallow this option from being displayed in the Chart View.

**Action: Display Inflation in the Chart View, and make it optional for the user to show/hide in chart view.**

**Comment by pampeanodev** [comment]
Adding inflation rate to the chart shouldn't be an issue. However, the fact that ranges where ß moves in the chart vs. where inflation (as a %) moves, vs where FIAT moves (specially this!), would make it impossible to compare in a single chart. In the future, we could consider adding a 2nd (or even a 3rd) chart with other stats, but that's a problem for future us :)
