### ISSUE TITLE
[BUG] Annual Estimated Buy

### ISSUE THREAD

**Issue by cobo2bofb** [pampeanodev/btcretirementcalc#15]
[BUG]

**Annual Estimated Buy not reflected in Chart View**

In chart view, no matter how many sats are bought yearly (Annual estimated buy), the orange line representing the amount of sats a user has won't increase overtime. In other words, the orange line in the chart remains unchanged no matter what. See below:

<img width="1280" alt="image" src="https://github.com/pampeanodev/btcretirementcalc/assets/100138874/498b5791-ae8c-45bc-a6c0-7d7b16a138fc">

**Action: Correct this bug to reflect the growing amount of sats the user hodls yearly in chart view.**

**Comment by pampeanodev** [comment]
If you hide the USD line by clicking in the label, you'll see how ₿ accumulation flows.
