### ISSUE TITLE
Retirement Age Incorrect

### ISSUE THREAD

**Issue by kegib** [pampeanodev/btcretirementcalc#30]
The retirement age is not showing correctly.  In the screenshot below, the Life Expectantly is 86, however the output  shows a retirement age of 48.

![image](https://github.com/pampeanodev/btcretirementcalc/assets/94768763/02a9e51e-a545-4eb8-9a66-f4a8bc8cb191)

**Comment by pampeanodev** [comment]
Hi @kegib,

The information you provided doesn't allow me to understand what's the issue you're trying to point out. 
Please expand the information with (at least) input parameters you put, expected result, actual result. 
Thanks.

**Comment by kegib** [comment]
I used my current age (47), and input life expectancy (86).  There is no place to input my retirement age, the calculator output shows a retirement age of 48.  I tried using multiple ages, and each time the retirement age was just 1 year from the current age. 

After adjusting other parameters, I realized the retirement age value is an indication of when you could retire based on the inputs. This was not clear initially.  Would it be possible to include another parameter for the user to indicate what age they would like to retire?

**Comment by pampeanodev** [comment]
This is how the calculation works: Based on the input params you set, it will give you your retirement age. There's no input parameter for an expected retirement age. We are considering adding a new mode to the calc, where you ask for a retirement age and the calc gives you a plan for your retirement, but we have no plans to include that in the immediate future.
Thans for the feedback!
